language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_98d9b3df05fd_key -iv $encrypted_98d9b3df05fd_iv
  -in secretkey.enc -out secretkey -d
- mkdir -p ~/.ssh/
- cp secretkey ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $server\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g bower
- bower install
script:
- 
- tar czf html.tar.gz *
after_success:
- scp html.tar.gz $login@$server:/home/$login/html/
- ssh $login@$server "tar xzf html.tar.gz"
env:
  global:
  - secure: F1Vs8qlCDtaFAlLS3T9bsRmrQy1lA56hRNGfYpXYREzSIHQ7ORLMdng993fCx7MH4J/rn3TbuZDhuIPAQXIe4jh+ROK1iav1LJKX5kGGjZnUz94DAwziXyrsTVV3VyjWP4Kc+O6WnwEaMQ6lXV6UuEsi5VW+WFZpoaEoJG8+5ng=
  - secure: aZbSOW4Afvp0ZmaChG+cUwkKtqt+bpLZfbnsKPYRqeqVnX2qTUykeCXoT0/UVjvTUSPXKDwdHL1chohfWzaZFpKFP43gjszWOagRA/pWEOeNFrXbfkoZUc1LOXGlrCle2sVybMjCb/Nat+dnGhTXP3j/U82h4dS53B8cvbkN5uA=
